# Profile information
name: Monita Ramirez
title: Data Scientist in Progress...
description: > # this means to ignore newlines until "baseurl:"
  Blog on Data Science, Git, Python, Pandas, Machine Learning, Regressions and much more
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "monitarb.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Social
facebook: #Add your Facebook
twitter: #Add your Twitter
google-plus: #Add your Google+
github: monitarb.github.io

# Contact form
email: monita.ramirezb@gmail.com

# Comments
discus-identifier: # Add your Disqus identifier

# Paginate
paginate: 5
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
include: [_pages]
